INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(1,4,'NA','True',1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(2,4,'NA','True',1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(3,4,'','True',1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(4,4, '','False',1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(5,4,'NA','False',1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(6,4,'NA','False',1,2)

INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(7,4,'d-MMM-yy','FALSE',1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(8,4,'dd-MMM-yyy','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(9,4,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(9,4,'Thanku','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(10,4,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(10,4,'Thank U Test','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(11,4,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(11,4,'Thank U 3 Test2','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(12,4,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(12,4,'Free Text','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(1,5,'NA','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(2,5,'NA','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(3,5,'','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(4,5,'','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(5,5,'NA','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(6,5,'NA','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(7,5,'dd-MMM-yyy','TRUE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(8,5,'dd-MMM-yyy','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(9,5,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(9,5,'Thanku','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(10,5,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(10,5,'Thank U Test','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(11,5,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(11,5,'Thank U 3 Test2','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(12,5,'','FALSE', 1,2)
INSERT INTO [MBarcodeSettings](SettingNo,BarcodeTemplateNo,SettingValue,IsActive,CompanyNo,StatusNo)VALUES(12,5,'Free Text','FALSE', 1,2)



