INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(1,1,'Master',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(2,2,'Sales',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(3,3,'Purchase',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(4,4,'Accounts && Inventory',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(5,5,'Reports',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(6,6,'Settings',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(7,7,'Utilities',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(8,8,'Hidden',0,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(9,1,'Stock',1,NULL,1,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(10,1,'Item',9,'Master.ItemMasterAE',NULL,1,'I',NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(11,3,'Category',9,'Master.ItemCategoryAE',NULL,1,NULL,2)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(12,2,'Department',9,'Master.ItemDepartmentAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(13,5,'Godown',9,'Master.GodownAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(14,4,'Brand / Group',9,'Master.ItemGroupAE',NULL,1,NULL,3)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(15,2,'Location',1,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(16,1,'Location',15,'Master.LocationsAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(17,2,'Country',15,'Master.CountryAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(18,3,'State',15,'Master.StateAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(19,4,'City',15,'Master.CityAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(20,5,'Area',15,'Master.AreaAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(21,3,'Account',1,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(22,1,'Customer',21,'Master.CustomerAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(23,2,'Supplier',21,'Master.SupplierAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(24,3,'Bank',21,'Master.BankAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(25,4,'Other Accounts',21,'Master.AccountsAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(26,5,'Tax Account',21,'Master.TaxAccountAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(27,6,'Tax Type',21,'Master.TaxTypeAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(28,1,'Sales',6,'Settings.SalesSetting',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(29,2,'Purchase',6,'Settings.PurchaseSetting',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(30,1,'GST %',39,'Settings.MultiItemsTaxSettingsAE',NULL,1,NULL,32)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(31,4,'Other',6,'Settings.OtherSetting',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(32,3,'Paytype',6,'Settings.PayTypeSetting',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(33,1,'Bill',2,'Vouchers.SalesBarcodeAE',NULL,1,'B',NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(34,1,'Purchase',3,'Vouchers.PurchaseAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(35,2,'Purchase Return',3,'Vouchers.PurchaseReturnAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(36,2,'Other Utilities',7,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(37,4,'Chque && Docket Printing',4,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(38,1,'Item Change',7,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(39,3,'Scheme',7,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(40,4,'Account',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(41,3,'Stock',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(42,1,'Sales',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(43,2,'Purchase',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(44,4,'Other',1,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(45,1,'UOM',44,'Master.UomAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(46,4,'Printing BarCode',7,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(47,1,'Multiple Barcode Print',46,'Utilities.MultipleBarCodePrint',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(48,2,'Weighing Barcode Print',46,'Utilities.WeighingBarCodePrint',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(49,3,'Opening Balances',4,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(50,1,'Customer',49,'Utilities.LedgerOpeningBalance',NULL,1,NULL,1)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(51,2,'Supplier',49,'Utilities.LedgerOpeningBalance',NULL,1,NULL,2)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(52,3,'Bank/Cash',49,'Utilities.LedgerOpeningBalance',NULL,1,NULL,3)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(53,4,'Tax Accounts',49,'Utilities.LedgerOpeningBalance',NULL,1,NULL,4)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(54,5,'Other Accounts',49,'Utilities.LedgerOpeningBalance',NULL,1,NULL,5)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(55,1,'Rate (Master)',38,'Utilities.ItemRateChange',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(56,2,'Inventory',4,NULL,NULL,1,NULL,23)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(57,6,'Opening Stock',49,'Utilities.OpeningStockAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(58,2,'Stock Inward',56,'Vouchers.StockInward',NULL,1,NULL,23)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(59,3,'Stock Outward',56,'Vouchers.StockInward',NULL,1,NULL,24)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(60,1,'Cash Denomination',36,'Utilities.CashDenomination',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(61,2,'User',44,'Master.User',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(62,3,'FirmMaster',44,'Master.FirmAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(63,14,'Registration Details',36,'Utilities.RegistrationAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(64,5,'Item Tax',6,'Master.ItemTaxSettingsAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(65,4,'Occupation',44,'Master.OccupationAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(66,5,'Qualification',44,'Master.QualificationAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(67,2,'Collection',2,'Vouchers.CollectionEntryAE',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(68,3,'Payment',3,'Vouchers.CollectionEntryAE',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(69,3,'Sales Return',2,'Vouchers.SalesReturnAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(70,16,'Server Settings',36,'Utilities.ServerRegistration',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(71,7,'Other Bank (Party''s)',21,'Master.OtherBankAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(72,8,'Other Bank Branch',21,'Master.BranchAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(73,5,'Export Stock Items',7,'Utilities.ExportStockItems',NULL,0,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(74,18,'End Of Day',36,'Master.EndDay',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(75,2,'Name && Description',38,'Utilities.ItemChange',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(76,5,'MIS Reports',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(77,20,'Dictionary',36,'Master.DictionaryAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(78,6,'Scheme',6,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(79,1,'MTD',78,'Settings.Loyalty.LoyaltyMTD',NULL,1,NULL,1)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(80,2,'TVB',78,'Settings.Loyalty.LoyaltyMTD',NULL,1,NULL,2)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(81,3,'TSKU',78,'Settings.Loyalty.LoyaltyPSKU',NULL,1,NULL,3)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(82,4,'TSKUC',78,'Settings.Loyalty.LoyaltyPSKU',NULL,1,NULL,4)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(83,5,'PSKU',78,'Settings.Loyalty.LoyaltyPSKU',NULL,1,NULL,5)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(84,20,'Item Activation',36,'Utilities.ItemTransferFromGlobalToLocal',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(85,22,'Import Items',36,'Utilities.ImportItems',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(86,6,'Scheme',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(87,7,'Stock Counting',6,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(88,12,'Stock Count Type',87,'Settings.StockCountTypeAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(89,13,'Inventory Count Schedule',87,'Settings.InventoryCountSchedule',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(90,4,'Physical Stock Entry',56,'Vouchers.PhysicalStockEntryAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(91,23,'Footer Bill Discount',78,'Master.FooterDiscount',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(92,23,'Item Level Discount',78,'Master.ItemLevelDiscount',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(93,2,'Scheme Activation',39,'Utilities.SchemeActivation',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(94,4,'StockTransfer',56,'Vouchers.StockTransfer',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(95,8,'Barcode Fields',6,'Settings.BarcodeSettings',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(96,9,'Barcode Template',6,'Master.BarcodeTemplateAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(97,25,'Activate Items All',36,'Utilities.ItemTransferFromGlobalToLocalAll',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(98,4,'Purchase Order',3,'Vouchers.PurchaseOrderAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(99,10,'Margin %',38,'Utilities.ItemMarginChange',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(100,7,'Margin Details',5,'Display.MarginDetails',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(101,26,'Seasonal Barcode Print',36,'Utilities.SeasonalBarcodePrint',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(102,1,'Expenses Entry',134,'Vouchers.ExpensesEntryAE',NULL,1,NULL,33)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(103,2,'Cash Receipt',134,'Vouchers.ExpensesEntryAE',NULL,1,NULL,27)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(104,6,'Customer Type',44,'Master.CustomerTypeAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(105,7,'Supp Category',44,'Master.SuppCategoryAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(106,8,'Customer Size',44,'Master.CustomerSizeAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(107,5,'Purchase APMC',3,'Vouchers.PurchaseAPMCAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(108,9,'Broker',21,'Master.BrokerAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(109,8,'GRN Reports',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(110,4,'Quotation Entry',2,'Vouchers.QuotationAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(111,9,'Quotation',5,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(112,6,'C-Form Details',7,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(113,1,'Sales',112,'Vouchers.VoucherFormDetails',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(114,2,'Purchase',112,'Vouchers.VoucherFormDetails',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(116,10,'Godown',6,'Settings.GodownSetting',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(117,4,'Quotation Rate',38,'Utilities.QuotationRateChange',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(118,7,'Delete Entrys',7,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(119,1,'Delete Quatation',118,'Utilities.DeleteQuatation',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(120,5,'Duplicate Bill Print',2,'Display.DuplicatBillPrint',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(121,31,'Cheque Printing',37,'Vouchers.ChequePrintingAE',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(122,32,'Cheque Details',37,'Utilities.ChequeDetailsAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(123,34,'Docket Printing',37,'Utilities.DocketPrinting',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(124,2,'Delete GRN Entrys',118,'Utilities.DeleteGRNEntry',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(125,3,'Delete Purchase Order',118,'Utilities.DeletePurchaseOrder',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(126,10,'Transporter',21,'Master.TransporterAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(127,6,'Sale Order',2,'Vouchers.SaleOrderAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(128,4,'DeleteTransaction',118,'Utilities.DeleteTransaction',NULL,1,NULL,1015)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(129,3,'Partywise Rate',38,'Utilities.PartyWiseRateChange',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(130,5,'Rate Variation %',38,'Utilities.RateVariationChange',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(131,3,'Cash Payment',134,'Vouchers.ExpensesEntryAE',NULL,1,NULL,34)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(132,5,'Stock Assembly',56,'Vouchers.StockAssembly',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(133,10,'Chart Dashboard',5,'Display.ChartDashBoard',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(134,1,'Accounts',4,NULL,NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(135,5,'DeleteTransaction Firmwise',118,'Utilities.DeleteTransaction',NULL,1,NULL,2015)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(136,8,'C Form %',38,'Settings.MultiItemsTaxSettingsAE',NULL,1,NULL,34)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(137,9,'CST %',38,'Settings.MultiItemsTaxSettingsAE',NULL,1,NULL,35)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(138,6,'Delete Payment',3,'Vouchers.DeleteCollectionEntry',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(139,7,'Delete Collection',2,'Vouchers.DeleteCollectionEntry',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(140,8,'Cash Book',2,'Vouchers.CashBookAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(141,11,'Cash Book Report',5,'Display.CashBook',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(142,1,'Sales Register',42,'Display.SalesRegisterSummary',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(143,1,'Purchase Register',43,'Display.SalesRegisterSummary',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(144,8,'Temp Transfer',7,'Utilities.TempTransfer',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(145,9,'SALES APMC',2,'Vouchers.SalesAPMC',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(146,1,'Ledger Book',40,'Display.LedgerBook',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(147,2,'Cash Book',40,'Display.CashBook',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(148,3,'Day Book',40,'Display.DayBook',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(149,4,'Bank Book',40,'Display.BankBook',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(150,3,'Partywise Itemwise Sales',42,'Display.LedgerItemWiseSalesDetails',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(151,1,'Itemwise Purchase',43,'Display.ItemWiseSalesDetails',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(152,3,'Partywise Itemwise Details',43,'Display.LedgerItemWiseSalesDetails',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(153,4,'Sales GST Details',42,'Display.TaxDetails',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(154,2,'Itemwise Sales',42,'Display.ItemWiseSalesDetails',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(155,4,'Purchase GST Details',43,'Display.TaxDetails',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(156,10,'Sales Bill AutoMobile',2,'Vouchers.SalesAutoAE',NULL,1,'B',15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(157,5,'Sales OutStanding',42,'Display.OutStanding',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(158,5,'Purchase OutStanding',43,'Display.OutStanding',NULL,1,NULL,9)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(159,9,'SalesMan',44,'Master.SalesmanAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(160,6,'APMC Sales Register',42,'Display.APMCRegisterSummary',NULL,1,NULL,15)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(161,1,'Stock Summary',41,'Display.StockSummary',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(162,2,'Stock Summary Main',41,'Display.StockSummaryMain',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(163,6,'Item Recipe',9,'Master.ItemRecipeAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(164,7,'Production',9,'Master.ProductionAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(165,8,'Item Master(Auto)',9,'Master.ItemMasterAUTOAE',NULL,1,'A',NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(166,11,'Quotation',2,'Vouchers.QuotationAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(167,9,'Rack',9,'Master.RackMasterAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(168,11,'Ledger Group',21,'Master.LedgerGroupAE',NULL,1,NULL,NULL)
INSERT INTO [MMenuMaster](SrNo, MenuID, MenuName, ControlMenu, NavigateURL, IsChildNode, IsAllow, ShortCutKey, ConstructorValue)VALUES(169,3,'Stock Summary HSNCode Wise',41,'Display.StockSummaryHSNCodeWise',NULL,1,NULL,NULL)
